"""Lock the vol-normalized drop label formula to the validated sweep formula.

The K=1.75 walk-forward AUC 0.598 result was generated by
`scripts/sweep_drop_vol_k.py` using:

    vol_20d = daily_ret.rolling(20).std() * sqrt(252)        # annualized
    vol_5d  = vol_20d / sqrt(252 / FORWARD_DAYS)
    label   = fwd_return < -K * vol_5d

If the prod label drifts from this, the validation result no longer applies.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from src.models.directional import (
    DEFAULT_DROP_VOL_K,
    DirectionalModel,
    FORWARD_DAYS,
    LABEL_MODE_ABSOLUTE,
    LABEL_MODE_EXCESS,
    LABEL_MODE_VOL_NORMALIZED,
    VALID_LABEL_MODES,
)


def _reference_label(close: np.ndarray, k: float) -> np.ndarray:
    """Independent reimplementation of sweep_drop_vol_k.py formula."""
    s = pd.Series(close)
    daily = s.pct_change()
    vol_20d = daily.rolling(20).std() * np.sqrt(252)
    vol_5d = vol_20d / np.sqrt(252.0 / FORWARD_DAYS)
    fwd = s.shift(-FORWARD_DAYS) / s - 1.0
    valid = fwd.notna() & vol_5d.notna() & (vol_5d > 0)
    label = np.where(valid, (fwd < -k * vol_5d).astype(int), np.nan)
    return label


def test_default_vol_k_matches_validated_research_constant():
    # Sweep selected K=1.75; do not drift this without re-running the walk-forward.
    assert DEFAULT_DROP_VOL_K == 1.75


def test_vol_normalized_in_valid_label_modes():
    assert LABEL_MODE_VOL_NORMALIZED in VALID_LABEL_MODES


def test_default_drop_label_mode_is_vol_normalized():
    m = DirectionalModel(direction="drop")
    assert m.label_mode == LABEL_MODE_VOL_NORMALIZED
    assert m.vol_k == DEFAULT_DROP_VOL_K


def test_rise_default_unchanged():
    m = DirectionalModel(direction="rise")
    assert m.label_mode == LABEL_MODE_EXCESS


def test_vol_normalized_rejects_rise_direction():
    with pytest.raises(ValueError, match="vol_normalized"):
        DirectionalModel(direction="rise", label_mode=LABEL_MODE_VOL_NORMALIZED)


def test_explicit_label_mode_overrides_default():
    m = DirectionalModel(direction="drop", label_mode=LABEL_MODE_ABSOLUTE)
    assert m.label_mode == LABEL_MODE_ABSOLUTE


def test_unknown_label_mode_rejected():
    with pytest.raises(ValueError, match="label_mode"):
        DirectionalModel(direction="drop", label_mode="nonsense")


def test_save_load_round_trips_vol_k(tmp_path):
    import pickle

    model_path = tmp_path / "m.pkl"
    m = DirectionalModel(model_path=model_path, direction="drop", vol_k=2.0)
    # Write a minimal pickle compatible with .save() — bypass training.
    with open(model_path, "wb") as f:
        pickle.dump(
            {
                "model": None,
                "feature_cols": m.feature_cols,
                "calibrator": None,
                "brier_score": None,
                "direction": "drop",
                "label_mode": LABEL_MODE_VOL_NORMALIZED,
                "vol_k": 2.0,
            },
            f,
        )
    m2 = DirectionalModel(model_path=model_path)
    m2.load()
    assert m2.vol_k == 2.0
    assert m2.label_mode == LABEL_MODE_VOL_NORMALIZED


def test_legacy_pickle_without_vol_k_defaults():
    """Old drop_v3 pickles predate vol_k. Loader must default rather than crash."""
    import pickle
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "legacy.pkl"
        with open(p, "wb") as f:
            pickle.dump(
                {
                    "model": None,
                    "feature_cols": [],
                    "calibrator": None,
                    "brier_score": None,
                    "direction": "drop",
                    "label_mode": LABEL_MODE_ABSOLUTE,
                    # no vol_k key
                },
                f,
            )
        m = DirectionalModel(model_path=p)
        m.load()
        assert m.vol_k == DEFAULT_DROP_VOL_K


def test_vol_normalized_label_matches_sweep_formula_synthetic():
    """End-to-end formula check against the sweep script's math."""
    rng = np.random.default_rng(7)
    # Geometric brownian motion-ish close series, single ticker, 400 days.
    n = 400
    rets = rng.normal(loc=0.0005, scale=0.015, size=n)
    close = 100.0 * np.exp(np.cumsum(rets))

    # Replicate the in-module label calculation (the snippet inside build_dataset).
    s = pd.Series(close)
    vol_20d_annualized = s.pct_change().rolling(20).std() * np.sqrt(252)
    fwd_return = s.shift(-FORWARD_DAYS) / s - 1.0
    vol_5d = vol_20d_annualized / np.sqrt(252.0 / FORWARD_DAYS)
    valid = fwd_return.notna() & vol_5d.notna() & (vol_5d > 0)
    k = DEFAULT_DROP_VOL_K
    impl_label = np.where(valid, (fwd_return < -k * vol_5d).astype(int), np.nan)

    ref_label = _reference_label(close, k)

    # Compare element-wise, treating NaN as equal-NaN.
    impl_s = pd.Series(impl_label)
    ref_s = pd.Series(ref_label)
    both_nan = impl_s.isna() & ref_s.isna()
    both_eq = (impl_s == ref_s) | both_nan
    assert both_eq.all(), f"{(~both_eq).sum()} mismatches"
