"""add alerts and alert_settings tables

Revision ID: 84290cd67c7d
Revises: 8612ba71ff2b
Create Date: 2026-03-13 18:13:56.326149
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '84290cd67c7d'
down_revision: Union[str, None] = '8612ba71ff2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('bot_token', sa.String(length=200), nullable=True),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Integer(), nullable=True),
    sa.Column('score_threshold', sa.Float(), nullable=True),
    sa.Column('alert_stop_loss', sa.Integer(), nullable=True),
    sa.Column('alert_target_hit', sa.Integer(), nullable=True),
    sa.Column('alert_high_conviction', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('acknowledged', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('alert_settings')
    # ### end Alembic commands ###
